### ISSUE TITLE
Namespace for Cluster Add-on: UI

### ISSUE THREAD

**Issue by NegatioN** [kelseyhightower/intro-to-kubernetes-workshop#11]
The supplied kube-ui-rc.yaml in the guide references a namespace with the name "kube-system", but i can't find any mention of making that namespace.

This in turn throws an error: 

Error from server: error when creating "kube-ui-rc.yaml": ReplicationController "kube-ui-v1" is forbidden: Namespace kube-system does not exist

**Comment by kbeecher** [comment]
I also have the same problem.

**Comment by NegatioN** [comment]
I'm thinking this might be an issue for those of us following the guide completely, even if we locate our server cluster on another region of GCE. 
Might this in turn lead to the certificate not functioning correctly?
I had to disable "ServiceAccount" from the kube-apiserver manifest to get things functioning.

Thanks for making the guide available to everyone though.

**Comment by kbeecher** [comment]
My colleague has contributed a fix: https://github.com/endocode/intro-to-kubernetes-workshop/commit/81819a8c370d383e4b2fcf1d818f8ccea1c3cb5f
